ipx::package_project -root_dir ./ip -vendor ISOLDE-CAR -library user -taxonomy /UserIP -set_current true -force
set_property company_url https://www.isolde-project.eu/ [ipx::current_core]
set_property vendor_display_name ISOLDE-CAR [ipx::current_core]
set_property core_revision 1 [ipx::current_core]
ipx::remove_user_parameter NrDmaMasters [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_ID_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_ADDR_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_DATA_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_AWUSER_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_ARUSER_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_WUSER_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_RUSER_WIDTH [ipx::current_core]
ipx::remove_user_parameter C_M_AXI_WIDE_BUSER_WIDTH [ipx::current_core]
ipx::create_xgui_files [ipx::current_core]
ipx::update_checksums [ipx::current_core]
ipx::check_integrity [ipx::current_core]
ipx::save_core [ipx::current_core]
